const blogPosts = [
  {
    id: 1,
    slug: "how-to-create-an-npm-package",
    title: "How To Create An NPM Package",
    excerpt: "A step-by-step guide to publishing a production-ready npm package with TypeScript, Prettier, CI, and more...",
    date: "2024-03-20",
    category: "TypeScript",
    readTime: "15 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["TypeScript", "npm", "Publishing"],
    content: require('./markdown/how-to-create-an-npm-package.md')
  },
  {
    id: 2,
    slug: "understanding-typescript",
    title: "Understanding TypeScript",
    excerpt: "A comprehensive guide to TypeScript and its benefits for building scalable applications with type safety and better developer experience...",
    date: "2024-03-18",
    category: "TypeScript",
    readTime: "7 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["TypeScript", "JavaScript", "Programming"],
    content: require('./markdown/understanding-typescript.md')
  },
  {
    id: 3,
    slug: "modern-css-techniques",
    title: "Modern CSS Techniques",
    excerpt: "Explore modern CSS features like Grid, Flexbox, and CSS Variables to create responsive and maintainable layouts...",
    date: "2024-03-15",
    category: "Web Development",
    readTime: "6 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["CSS", "Web Development", "Frontend"],
    content: require('./markdown/modern-css-techniques.md')
  },
  {
    id: 4,
    slug: "javascript-es2023-features",
    title: "JavaScript ES2023 Features",
    excerpt: "Discover the latest features in JavaScript ES2023 and how to use them in your projects...",
    date: "2024-03-12",
    category: "JavaScript",
    readTime: "8 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["JavaScript", "ES2023", "Web Development"],
    content: require('./markdown/javascript-es2023-features.md')
  },
  {
    id: 5,
    slug: "deploying-with-netlify",
    title: "Deploying with Netlify",
    excerpt: "A step-by-step guide to deploying your web applications using Netlify for fast and secure hosting...",
    date: "2024-03-10",
    category: "Web Development",
    readTime: "5 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["Netlify", "Deployment", "Web Development"],
    content: require('./markdown/deploying-with-netlify.md')
  },
  {
    id: 6,
    slug: "react-hooks-deep-dive",
    title: "React Hooks Deep Dive",
    excerpt: "Master React Hooks with practical examples and advanced patterns for state and effect management...",
    date: "2024-03-08",
    category: "React",
    readTime: "9 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["React", "Hooks", "JavaScript"],
    content: require('./markdown/react-hooks-deep-dive.md')
  },
  {
    id: 7,
    slug: "typescript-generics-explained",
    title: "TypeScript Generics Explained",
    excerpt: "Understand TypeScript generics and how they help you write reusable and type-safe code...",
    date: "2024-03-06",
    category: "TypeScript",
    readTime: "6 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["TypeScript", "Generics", "Programming"],
    content: require('./markdown/typescript-generics-explained.md')
  },
  {
    id: 8,
    slug: "building-responsive-layouts",
    title: "Building Responsive Layouts",
    excerpt: "Tips and tricks for building responsive layouts that look great on any device...",
    date: "2024-03-04",
    category: "Web Development",
    readTime: "7 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["CSS", "Responsive Design", "Frontend"],
    content: require('./markdown/building-responsive-layouts.md')
  },
  {
    id: 9,
    slug: "javascript-promises-async-await",
    title: "JavaScript Promises & Async/Await",
    excerpt: "A practical guide to mastering Promises and async/await in JavaScript for better asynchronous code...",
    date: "2024-03-02",
    category: "JavaScript",
    readTime: "8 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["JavaScript", "Async", "Promises"],
    content: require('./markdown/javascript-promises-async-await.md')
  },
  {
    id: 10,
    slug: "react-context-api-in-practice",
    title: "React Context API in Practice",
    excerpt: "Learn how to use the React Context API for state management in modern React apps...",
    date: "2024-02-28",
    category: "React",
    readTime: "6 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["React", "Context API", "State Management"],
    content: require('./markdown/react-context-api-in-practice.md')
  },
  {
    id: 11,
    slug: "typescript-vs-javascript-when-to-use-what",
    title: "TypeScript vs JavaScript: When to Use What?",
    excerpt: "A comparison of TypeScript and JavaScript, and guidance on when to use each in your projects...",
    date: "2024-02-25",
    category: "TypeScript",
    readTime: "7 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["TypeScript", "JavaScript", "Programming"],
    content: require('./markdown/typescript-vs-javascript-when-to-use-what.md')
  },
  {
    id: 12,
    slug: "css-grid-vs-flexbox",
    title: "CSS Grid vs Flexbox",
    excerpt: "Understand the differences between CSS Grid and Flexbox and when to use each for layout...",
    date: "2024-02-22",
    category: "Web Development",
    readTime: "5 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["CSS", "Grid", "Flexbox"],
    content: require('./markdown/css-grid-vs-flexbox.md')
  },
  {
    id: 13,
    slug: "javascript-array-methods-you-should-know",
    title: "JavaScript Array Methods You Should Know",
    excerpt: "Explore essential JavaScript array methods with examples for everyday coding...",
    date: "2024-02-20",
    category: "JavaScript",
    readTime: "6 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["JavaScript", "Arrays", "Programming"],
    content: require('./markdown/javascript-array-methods-you-should-know.md')
  },
  {
    id: 14,
    slug: "react-performance-optimization",
    title: "React Performance Optimization",
    excerpt: "Best practices and techniques for optimizing the performance of your React applications...",
    date: "2024-02-18",
    category: "React",
    readTime: "8 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["React", "Performance", "Optimization"],
    content: require('./markdown/react-performance-optimization.md')
  },
  {
    id: 15,
    slug: "typescript-utility-types",
    title: "TypeScript Utility Types",
    excerpt: "A guide to TypeScript's built-in utility types and how to use them effectively...",
    date: "2024-02-15",
    category: "TypeScript",
    readTime: "5 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["TypeScript", "Utility Types", "Programming"],
    content: require('./markdown/typescript-utility-types.md')
  },
  {
    id: 16,
    slug: "accessible-web-design",
    title: "Accessible Web Design",
    excerpt: "Learn the principles of accessible web design and how to make your sites usable for everyone...",
    date: "2024-02-12",
    category: "Web Development",
    readTime: "7 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["Accessibility", "Web Design", "Frontend"],
    content: require('./markdown/accessible-web-design.md')
  },
  {
    id: 17,
    slug: "javascript-closures-explained",
    title: "JavaScript Closures Explained",
    excerpt: "A deep dive into closures in JavaScript and how to use them effectively...",
    date: "2024-02-10",
    category: "JavaScript",
    readTime: "6 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["JavaScript", "Closures", "Programming"],
    content: require('./markdown/javascript-closures-explained.md')
  },
  {
    id: 18,
    slug: "react-router-v6-guide",
    title: "React Router v6 Guide",
    excerpt: "Everything you need to know about routing in React apps using React Router v6...",
    date: "2024-02-08",
    category: "React",
    readTime: "7 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["React", "Router", "Web Development"],
    content: require('./markdown/react-router-v6-guide.md')
  },
  {
    id: 19,
    slug: "typescript-for-beginners",
    title: "TypeScript for Beginners",
    excerpt: "A beginner-friendly introduction to TypeScript and how to get started...",
    date: "2024-02-05",
    category: "TypeScript",
    readTime: "5 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["TypeScript", "Beginner", "Programming"],
    content: require('./markdown/typescript-for-beginners.md')
  },
  {
    id: 20,
    slug: "building-forms-with-react-hook-form",
    title: "Building Forms with React Hook Form",
    excerpt: "How to build robust and user-friendly forms in React using React Hook Form...",
    date: "2024-02-02",
    category: "React",
    readTime: "8 min read",
    image: require('../../Assets/about.png'),
    author: "Himanshu Chaudhary",
    tags: ["React", "Forms", "React Hook Form"],
    content: require('./markdown/building-forms-with-react-hook-form.md')
  }
];

export default blogPosts; 